### ISSUE TITLE
403 issue

### ISSUE THREAD

**Issue by seanngpack** [antonmedv/gatsby-source-google-analytics-reporting-api#2]
Hi, thanks for making this plugin!
I'm having trouble implementing it. I've read many resources on how to use google APIs before submitting this ticket, I just can't get it to work. My issue is that I keep getting a 403 error when I run `gatsby develop`:

```
Error: Request failed with status code 403

  - createError.js:16 createError
    [lengjai]/[axios]/lib/core/createError.js:16:15

  - settle.js:18 settle
    [lengjai]/[axios]/lib/core/settle.js:18:12

  - http.js:201 Unzip.handleStreamEnd
    [lengjai]/[axios]/lib/adapters/http.js:201:11

  - next_tick.js:63 process._tickCallback
    internal/process/next_tick.js:63:19
```

gatsby-config.js
```
{
      resolve: `gatsby-source-google-analytics-reporting-api`,
      options: {
        email: 'eample@example.iam.gserviceaccount.com',
        key: '-----BEGIN PRIVATE KEY-----\ there's a lot inside of this key==\n-----END PRIVATE KEY-----\n',
        viewId: `000000000`,
        startDate: `2017-01-01`,
      }
    },
```

So I registered for the google reporting API and downloaded the key info as JSON when it prompted me to. Inside the JSON file I had all the information such as private key and client email. I removed those in my code for privacy. I gathered the viewId from my google analytics page. So I have a couple things that could potentially cause the issue:

1. Maybe my private key is wrong? It is insanely massive and has \n line breaks scattered along with that BEGIN PRIVATE KEY statement.
2. The plugin is outdated? The latest Analytics reporting API is in v4.

Thanks!
Sean

**Comment by antonmedv** [comment]
1. 403 is forbidden, so yes looks like your key is wrong.
2. Plugin is working for me really well. Just redeployed https://medv.io

This is my setup:

```js
    {
      resolve: `gatsby-source-google-analytics-reporting-api`,
      options: {
        email: json('google-api.json').client_email,
        key: json('google-api.json').private_key,
        viewId: `1234567890`,
        startDate: `2009-01-01`,
      }
    }
```

There google-api.json is downloaded from google api keys.

**Comment by seanngpack** [comment]
@antonmedv Thanks for the response! I have two more questions, 
1. how did you get the json function to work? **json(**'google-api.json'**)**.client_email 
2. does your key also start with `-----BEGIN PRIVATE KEY-----\n`?

Because I don't know how to solve 1., I wrapped my key in a JSON.stringify function with no luck still, it's saying there is no key or keyFile so it must not be finding my auth.json file: 
`key: JSON.stringify(('auth.json').private_key), `

**Comment by antonmedv** [comment]
1. https://github.com/antonmedv/medv.io/blob/master/gatsby-config.js#L132-L134
2. Yes, of course

**Comment by seanngpack** [comment]
Awesome, I found my issue! 
I had to add my google service account to my google analytics account and give it read/write permissions. Everything works now!!
